[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
MONGODB_URI = "mongodb://localhost:27017/mlscraper"
API_HOST = "0.0.0.0"
MAX_CONCURRENT_JOBS = "5"
REQUEST_DELAY = "1.0"
MAX_RETRIES = "3"
RATE_LIMIT_PER_MINUTE = "60"
LOG_LEVEL = "INFO"
NODE_ENV = "production"
